/*
ALUMNO: Cazares Godínez Brian Xavier
FECHA: 06 de Abril de 2022
DESCRIPCIÓN: Interfaz de programa del algoritmo de planificación round robin (RR).
 */
package arr;
//import Imagenes.InterfazProceso;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author brianxavier
 */
public class InicioSesion extends javax.swing.JFrame {

    //EXPLICAR CÓDIGO (Insertar imagen de fondo)
    FondoPanel fondo = new FondoPanel();

    public InicioSesion() {

        //EXPLICAR CÓDIGO (Insertar imagen de fondo)
        this.setContentPane(fondo);

        initComponents();

        //EXPLICAR CÓDIGO (Ocultar un botón cuando se presione otro)
        this.btn5.setVisible(false);

        //EXPLICAR CÓDIGO (Insertar imagen de fondo)
        btn1.setIcon(setIcono("/imagenes/Ingresar.png", btn1));
        btn1.setPressedIcon(setIconoPresionado("/imagenes/Ingresar.png", btn1, 5, 5));

        btn2.setIcon(setIcono("/imagenes/Limpiar.png", btn2));
        btn2.setPressedIcon(setIconoPresionado("/imagenes/Limpiar.png", btn2, 5, 5));

        btn3.setIcon(setIcono("/imagenes/Salir.png", btn3));
        btn3.setPressedIcon(setIconoPresionado("/imagenes/Salir.png", btn3, 5, 5));

        btn4.setIcon(setIcono("/imagenes/Mostrar.png", btn4));
        btn4.setPressedIcon(setIconoPresionado("/imagenes/Mostrar.png", btn4, 5, 5));

        btn5.setIcon(setIcono("/imagenes/Ocultar.png", btn5));
        btn5.setPressedIcon(setIconoPresionado("/imagenes/Ocultar.png", btn5, 5, 5));

        //EXPLICAR CÓDIGO (Quitar borde a un botón)
        transparenciaButton();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        CUsuario = new javax.swing.JTextField();
        btn1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        CContrasena = new javax.swing.JPasswordField();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        getContentPane().setLayout(null);

        btn2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn2);
        btn2.setBounds(600, 400, 60, 60);

        btn3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn3);
        btn3.setBounds(710, 400, 60, 60);

        CUsuario.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        CUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CUsuarioActionPerformed(evt);
            }
        });
        CUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CUsuarioKeyTyped(evt);
            }
        });
        getContentPane().add(CUsuario);
        CUsuario.setBounds(490, 270, 280, 40);

        btn1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        btn1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btn1KeyTyped(evt);
            }
        });
        getContentPane().add(btn1);
        btn1.setBounds(490, 400, 60, 60);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 50)); // NOI18N
        jLabel1.setText("INGRESAR");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(500, 200, 270, 40);

        CContrasena.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        getContentPane().add(CContrasena);
        CContrasena.setBounds(490, 330, 280, 40);

        btn4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn4MousePressed(evt);
            }
        });
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn4);
        btn4.setBounds(780, 330, 40, 40);

        btn5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn5MousePressed(evt);
            }
        });
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn5);
        btn5.setBounds(780, 330, 40, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //CÓDIGO A EXPLICAR (Ajustar imagen a un botón)
    public Icon setIcono(String url, JButton boton) {
        ImageIcon icon = new ImageIcon(getClass().getResource(url));
        int ancho = boton.getWidth();
        int alto = boton.getHeight();
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));
        return icono;
    }

    //CÓDIGO A EXPLICAR (Ajustar imagen a un botón)
    public Icon setIconoPresionado(String url, JButton boton, int ancho, int altura) {
        ImageIcon icon = new ImageIcon(getClass().getResource(url));
        int width = boton.getWidth() - ancho;
        int height = boton.getHeight() - altura;
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(width, height, Image.SCALE_DEFAULT));
        return icono;
    }

    //CÓDIGO A EXPLICAR (Quitar borde a un botón)
    public void transparenciaButton() {
        btn1.setOpaque(false);
        btn1.setContentAreaFilled(false);
        btn1.setBorderPainted(false);
        btn2.setOpaque(false);
        btn2.setContentAreaFilled(false);
        btn2.setBorderPainted(false);
        btn3.setOpaque(false);
        btn3.setContentAreaFilled(false);
        btn3.setBorderPainted(false);
        btn4.setOpaque(false);
        btn4.setContentAreaFilled(false);
        btn4.setBorderPainted(false);
        btn5.setOpaque(false);
        btn5.setContentAreaFilled(false);
        btn5.setBorderPainted(false);

    }

    //CÓDIGO INSERTAR IMAGEN DE FONDO (Inserta una imagen de fondo)
    class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/imagenes/Verde.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }

    //CÓDIGO LIMPIAR TEXTOS (Limpia los textos ya escritos en los paneles)
    private void LimpiarTextos() {
        CUsuario.setText(null);
        CContrasena.setText(null);

    }

    private void CUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CUsuarioActionPerformed

    }//GEN-LAST:event_CUsuarioActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn3ActionPerformed

    //EXPLICAR CÓDIGO (Rango de valores permitidos en una casilla de texto con código ascii)
    private void CUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CUsuarioKeyTyped
        if (evt.getKeyChar() >= 32 && evt.getKeyChar() <= 45
                || evt.getKeyChar() >= 47 && evt.getKeyChar() <= 47
                || evt.getKeyChar() >= 58 && evt.getKeyChar() <= 64
                || evt.getKeyChar() >= 91 && evt.getKeyChar() <= 94
                || evt.getKeyChar() >= 96 && evt.getKeyChar() <= 96
                || evt.getKeyChar() >= 123 && evt.getKeyChar() <= 255) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "No se permiten caracteres especiales");
        }
    }//GEN-LAST:event_CUsuarioKeyTyped

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        LimpiarTextos();

    }//GEN-LAST:event_btn2ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        String user = CUsuario.getText();
        String usuario = "rr", contraseña = "12345";
        String pass = new String(CContrasena.getPassword());
        if (user.equals(usuario) && pass.equals(contraseña)) {
            InterfazProceso Ingresar = new InterfazProceso();
            Ingresar.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "EL USUARIO/CONTRASEÑA ESTÁ(N) INCORRECTOS");
        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_btn1KeyTyped

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed

    }//GEN-LAST:event_btn4ActionPerformed

    private void btn4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn4MousePressed
        btn4.setVisible(false);
        btn5.setVisible(true);
        CContrasena.setEchoChar((char) 0);
    }//GEN-LAST:event_btn4MousePressed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5MousePressed
        btn4.setVisible(true);
        btn5.setVisible(false);
        CContrasena.setEchoChar('*');
    }//GEN-LAST:event_btn5MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField CContrasena;
    private javax.swing.JTextField CUsuario;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
